package huit2017.entity;

import java.util.Date;

public class Advertisement {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.ad_id
     *
     * @mbg.generated Sun May 21 10:20:12 JST 2017
     */
    private Integer adId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.img_path
     *
     * @mbg.generated Sun May 21 10:20:12 JST 2017
     */
    private String imgPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.created_at
     *
     * @mbg.generated Sun May 21 10:20:12 JST 2017
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.updated_at
     *
     * @mbg.generated Sun May 21 10:20:12 JST 2017
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.ad_id
     *
     * @return the value of advertisement.ad_id
     *
     * @mbg.generated Sun May 21 10:20:12 JST 2017
     */
    public Integer getAdId() {
        return adId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.ad_id
     *
     * @param adId the value for advertisement.ad_id
     *
     * @mbg.generated Sun May 21 10:20:12 JST 2017
     */
    public void setAdId(Integer adId) {
        this.adId = adId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.img_path
     *
     * @return the value of advertisement.img_path
     *
     * @mbg.generated Sun May 21 10:20:12 JST 2017
     */
    public String getImgPath() {
        return imgPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.img_path
     *
     * @param imgPath the value for advertisement.img_path
     *
     * @mbg.generated Sun May 21 10:20:12 JST 2017
     */
    public void setImgPath(String imgPath) {
        this.imgPath = imgPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.created_at
     *
     * @return the value of advertisement.created_at
     *
     * @mbg.generated Sun May 21 10:20:12 JST 2017
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.created_at
     *
     * @param createdAt the value for advertisement.created_at
     *
     * @mbg.generated Sun May 21 10:20:12 JST 2017
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.updated_at
     *
     * @return the value of advertisement.updated_at
     *
     * @mbg.generated Sun May 21 10:20:12 JST 2017
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.updated_at
     *
     * @param updatedAt the value for advertisement.updated_at
     *
     * @mbg.generated Sun May 21 10:20:12 JST 2017
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}