package huit2017.entity;

import java.util.Date;

public class Bbs {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs.bbs_id
     *
     * @mbg.generated Sun May 21 10:20:12 JST 2017
     */
    private Integer bbsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs.user_id
     *
     * @mbg.generated Sun May 21 10:20:12 JST 2017
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs.comment
     *
     * @mbg.generated Sun May 21 10:20:12 JST 2017
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs.created_at
     *
     * @mbg.generated Sun May 21 10:20:12 JST 2017
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs.updated_at
     *
     * @mbg.generated Sun May 21 10:20:12 JST 2017
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs.bbs_id
     *
     * @return the value of bbs.bbs_id
     *
     * @mbg.generated Sun May 21 10:20:12 JST 2017
     */
    public Integer getBbsId() {
        return bbsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs.bbs_id
     *
     * @param bbsId the value for bbs.bbs_id
     *
     * @mbg.generated Sun May 21 10:20:12 JST 2017
     */
    public void setBbsId(Integer bbsId) {
        this.bbsId = bbsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs.user_id
     *
     * @return the value of bbs.user_id
     *
     * @mbg.generated Sun May 21 10:20:12 JST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs.user_id
     *
     * @param userId the value for bbs.user_id
     *
     * @mbg.generated Sun May 21 10:20:12 JST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs.comment
     *
     * @return the value of bbs.comment
     *
     * @mbg.generated Sun May 21 10:20:12 JST 2017
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs.comment
     *
     * @param comment the value for bbs.comment
     *
     * @mbg.generated Sun May 21 10:20:12 JST 2017
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs.created_at
     *
     * @return the value of bbs.created_at
     *
     * @mbg.generated Sun May 21 10:20:12 JST 2017
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs.created_at
     *
     * @param createdAt the value for bbs.created_at
     *
     * @mbg.generated Sun May 21 10:20:12 JST 2017
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs.updated_at
     *
     * @return the value of bbs.updated_at
     *
     * @mbg.generated Sun May 21 10:20:12 JST 2017
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs.updated_at
     *
     * @param updatedAt the value for bbs.updated_at
     *
     * @mbg.generated Sun May 21 10:20:12 JST 2017
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}