package huit2017.mapper;

import huit2017.entity.Bbs;
import huit2017.entity.BbsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BbsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs
     *
     * @mbg.generated Sun May 21 10:20:12 JST 2017
     */
    long countByExample(BbsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs
     *
     * @mbg.generated Sun May 21 10:20:12 JST 2017
     */
    int deleteByExample(BbsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs
     *
     * @mbg.generated Sun May 21 10:20:12 JST 2017
     */
    int deleteByPrimaryKey(Integer bbsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs
     *
     * @mbg.generated Sun May 21 10:20:12 JST 2017
     */
    int insert(Bbs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs
     *
     * @mbg.generated Sun May 21 10:20:12 JST 2017
     */
    int insertSelective(Bbs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs
     *
     * @mbg.generated Sun May 21 10:20:12 JST 2017
     */
    List<Bbs> selectByExample(BbsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs
     *
     * @mbg.generated Sun May 21 10:20:12 JST 2017
     */
    Bbs selectByPrimaryKey(Integer bbsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs
     *
     * @mbg.generated Sun May 21 10:20:12 JST 2017
     */
    int updateByExampleSelective(@Param("record") Bbs record, @Param("example") BbsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs
     *
     * @mbg.generated Sun May 21 10:20:12 JST 2017
     */
    int updateByExample(@Param("record") Bbs record, @Param("example") BbsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs
     *
     * @mbg.generated Sun May 21 10:20:12 JST 2017
     */
    int updateByPrimaryKeySelective(Bbs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs
     *
     * @mbg.generated Sun May 21 10:20:12 JST 2017
     */
    int updateByPrimaryKey(Bbs record);
}